#4 feature like functionaliteit driezie
driezie/pleasurable-ui pull request #11
Opened 2024-05-17 08:19 UTC by driezie

## Beschrijving

Ik heb 3 modules aangemaakt in mijn code. Hierbij heb ik algemene documentaties bij elke issue geschreven over wat de functionaliteit is. Hierbij heb ik ook de POST functie gefixed voor de server sided client.

Issues Gefixed

Resolved [ #8 favoritesManager.js Module](https://github.com/users/driezie/projects/10?pane=issue&itemId=62998444)
Resolved [ #9 fetchManager.js module](https://github.com/users/driezie/projects/10/views/1?pane=issue&itemId=62998564)
Resolved [ #10 likeChecker.js Module](https://github.com/users/driezie/projects/10/views/1?pane=issue&itemId=62998590)

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation (README and/or Wiki)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-05-17 09:27 UTC, berrzek commented
- Je instructies heb je neergezet, het is alleen nog niet helemaal duidelijk wat hier de bedoeling van is. Kijk nog eens naar de slides van Koop, daarin staat wat de bedoeling is.
- Je vertelt ook dat er code-afspraken zijn gemaakt, ik kan deze alleen niet terugvinden, waar staan die?
- Is er een ontwerp/design dat je hebt gemaakt waar ik kan zien of dat wat je gebouwd hebt overeenkomt?
Dit hoort ook in een PR

2024-05-17 09:33 UTC, suustenvoorde commented
Je website is wel responsive, maar niet mobile-first opgebouwd. Let hier op de volgende sprint, bouw je app altijd mobile-first.

2024-05-17 09:37 UTC, ju5tu5 requested changes
Best een groot _pull-request_, probeer voortaan eerder een request te doen. (i know.. dit was de regel)

Loop de comments op bestanden door en schiet issues in...

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/favoritesManager.js
Nette functionele compositie! Je hebt extra functies in losse modules neergezet in de helpers map.

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/favoritesManager.js
Snap je async/await goed? Zo niet is het handig de hoofdstukken over async uit 'eloquent javascript' op 'you don't know JS' te lezen.

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/fetchManager.js
Again.. supertof!

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/likeChecker.js
> +    console.log('isLiked: ', isLiked);
Haal de logs weg voor je code live zet..

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/likeChecker.js
> +    console.log('isLikedId: ', isLikedId);
Hier ook...

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/fetchManager.js
> +    console.log(`Successfully used ${method} request at ${url}`);
Haal logs weg voor je code live zet...

2024-05-17 09:37 UTC, ju5tu5 commented on helpers/likeChecker.js
> +    const isLiked = array.some(likedPlaylist => likedPlaylist.playlist === playlist.id);
Heel tof dat je ```some()``` gebruikt, deze stopt als er één value door het filter komt. Dat scheelt heel veel parse tijd..

2024-05-17 09:37 UTC, ju5tu5 commented on public/js/main.js
> +const forms = document.querySelectorAll('form');
Zet variabeledefinities helemaal bovenaan je bestand. Daarna de opdrachten die jouw code in werking zetten. Daarna al je functies.

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/cloud-save.svg
Heb je deze SVG door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/heart-filled.svg
Heb je deze SVG door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/heart.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/local-save.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/lock.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/music-note.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/play-orange.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on public/svg/play.svg
SVGOMG

2024-05-17 09:37 UTC, ju5tu5 commented on server.js
>  const apiUrl = "https://fdnd-agency.directus.app/items";
Variabele declaratie bovenin! (na imports)

2024-05-17 09:37 UTC, ju5tu5 commented on server.js
> +  console.log(likedPlaylistsResponse); // Log the response
logs weg voor live!

2024-05-17 09:37 UTC, ju5tu5 commented on server.js
> +  console.log(`Post request received with: ${itemId} and ${isLiked} and ${isLikedId}`);
!!

2024-05-17 09:37 UTC, ju5tu5 commented on server.js
> +  const playlistsResponse = await makeFetchRequest(playlistsAPI, 'GET');
Meerdere malen ```await``` na elkaar vertraagd enorm. Probeer eens in GraphQL te duiken, je kunt dan meerdere aanvragen tegelijk doen en precies datgene ophalen wat je nodig hebt..

2024-05-17 09:37 UTC, ju5tu5 commented on server.js
>    const playlistsWithLikedStatus = playlists.map(playlist => {
mooi ge```map```ped!

2024-05-17 09:37 UTC, ju5tu5 commented on views/index.ejs
Heb je de inlined SVG's door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 09:38 UTC, driezie commented
@suustenvoorde 
> Je website is wel responsive, maar niet mobile-first opgebouwd. Let hier op de volgende sprint, bouw je app altijd mobile-first.

Ik heb hier wel mobile first begonnen met het programeren. Ik heb speciaal in het begin van de eerste spring van Tumi Mundo besloten om `max-width` te gebruiken. Dit zegt niks over of ik wel of niet mobile-first heb gewerkt. En dit is dan ook wel heel laat verteld want ik maak al gebruik van deze `max-width` vanaf het begin van dit gehele project.

2024-05-19 12:19 UTC, driezie commented
@latoyaln 
> Je code werkt goed ook met JS uit doet de like het. Toen Rukiya dit ging testen voegde hij 2 playlists toe in plaats van alleen degene die je aanklikte. Ik weet niet zeker of dat ligt aan te snel klikken of dat je hier nog eens naar kan kijken.


Ik heb dit issue niet. Had je misschien niet een oudere code gebruikt? Ik heb hier niks aan. Kan je de volgende keer melden hoe je dit probleem hebt laten maken en wat je uiteindelijk hebt gedaan?

2024-05-19 12:21 UTC, driezie commented on server.js
> +  const playlistsResponse = await makeFetchRequest(playlistsAPI, 'GET');
Krijgen we hier ook les over hoe we dit kunnen gebruiken in ons project door middel van deze 'GraphQL'? Of een linkje waar dit voor mij duidelijk beschreven staat?

2024-05-22 12:43 UTC, driezie commented
# Fixes
Ik heb fixes op deze pull request gedaan. Hier zijn de volgende dingen die ik heb veranderd.

### Console logs weggehaald
Als eerste commit hebben we console logs weggehaald. Deze waren niet nodig.

### Fotos betere kwaliteit 
Ik heb de fotos een betere kwaliteit gegeven door een avif en een webp mogelijkheid te geven. Dit zorgt ervoor dat de pagina minder data hoeft te gebruiken en sneller kan inladen

Hier is een voorbeeld
```ejs
<picture>
    <source srcset="link-to-url?format=avif" type="image/avif">
    <source srcset="link-to-url?format=webp" type="image/webp">
    <img src="link-to-url" alt="play button" height="40" width="40">
</picture>

```

### SVG images door Jake Archibalds SVGOMG heen halen.
Ik ben hier op de website eerst alle SVG's door Jake Archibalds SVGOMG heen gehaald. Hierna heb ik de meeste in Directus gestopt. Hierdoor kan ik zoals je ziet bij de issue hierboven dat ik nu gebruik kan maken met avif en webp op de website.

Deze issue hoort bij #15 

### Animaties
Ik heb animaties toegevoegd aan de knoppen van de playknop en de like knop. Hierbij kan je goed zien of je iets hebt geliked. Gedrukt hebt en zien dat de like wordt geladen.

Deze issue hoort bij #4 

### Client side functie werkend
Ik heb de complete code opnieuw doorgelopen en samen met de docenten op een goed resultaat gekomen. Hierbij heb ik veranderingen gemaakt zodat nu ook voor de tweede keer klikken de client side werkt.

### Await fix
Ik heb bij deze maar 1 code veranderd waarvan ik zeker wist dat hierbij de performance sneller wordt. Als je hier nog issues bij vind kan je het opnieuw mij laten weten!

Deze issue hoort bij #22 

# Hoe heb ik dit getest?
### Javascript uitzetten door middel van "Web developer"

![Screenshot 2024-05-22 at 14 35 56](https://github.com/driezie/pleasurable-ui/assets/80174866/820b6e9f-1385-44e6-9b02-ecba2e7318ad)

Hierbij heb ik de Javascript uitgezet tests geprobeerd.

### Testen op verschillende devices

![Screenshot 2024-05-22 at 14 39 26](https://github.com/driezie/pleasurable-ui/assets/80174866/116128b5-6804-487d-85c4-c88773d7281a)

### Lighthouse test

![Screenshot 2024-05-22 at 14 40 25](https://github.com/driezie/pleasurable-ui/assets/80174866/211b81e9-5427-4806-9da3-0033573d72c6)



## Credits

> @ju5tu5 @berrzek @suustenvoorde @RukiyaTossou Bedankt voor de feedback die is gestuurd!

2024-05-29 08:24 UTC, merged